enum ResponseTypes {
  FIELD_ERRORS,
  INVALID_CREDENTIALS,
  USING_GOOGLE_SERVICE,
  WAITING_VERIFY_EMAIL,
  INTERNAL_ERROR,
  USER_WITH_EMAIL_NOTFOUND
}

Map<String, ResponseTypes> errorTypeMap = {
  'FIELD_ERRORS': ResponseTypes.FIELD_ERRORS,
  'INVALID_CREDENTIALS': ResponseTypes.INVALID_CREDENTIALS,
  'USING_GOOGLE_SERVICE': ResponseTypes.USING_GOOGLE_SERVICE,
  "WAITING _VERIFY_EMAIL": ResponseTypes.WAITING_VERIFY_EMAIL,
  "INTERNAL_ERROR": ResponseTypes.INTERNAL_ERROR,
  "USER_WITH_EMAIL_NOTFOUND": ResponseTypes.USER_WITH_EMAIL_NOTFOUND
};